### ISSUE TITLE
Trained Weights

### ISSUE THREAD

**Issue by ofirkris** [phillips96/CRA-Inpainting#1]
Hello, thanks for sharing this great project! well done.
I'd like to test it, can you kindly share the trained weights with me?

ofirseo @ gmail.com

**Comment by ofirkris** [comment]
Also, how is this implementation different than this one: https://github.com/Atlas200dk/sample-imageinpainting-HiFill
and have you trained on Places2 or other datasets?

**Comment by phillips96** [comment]
So the examples are from a simple data set of 800 512x512 images, just to check it works. It's currently training on the Places Dataset and once it is ready, I'll upload the weights! 

And with regards to HiFill, the architecture is largely the same, however it's hard to tell exactly as the source code isn't available (unless I'm mistaken).

It's a GAN style where the discriminator is transferred from VGG16, and the generator is trained to create a coarse representation at first, and then combines this with the attention and aggregation mechanisms to create the final output. There's also a handful of residual connections, but like I said it's hard to determine exact implementations.

**Comment by ofirkris** [comment]
Awesome!
The code of HiFill is available here - and results are quite decent compared to Pepsi++ which I've implemented
https://github.com/Atlas200dk/sample-imageinpainting-HiFill/tree/master/Huawei_Ascend

Problem that the NN isn't consistent and will give terrible results occasionally

**Comment by phillips96** [comment]
Hello, I have updated the model in `Examples/Model` directory. Please infer as described in `README.md`. As it currently stands, the model/dataloader are defined in channels first mode. This limits you to infer ONLY on GPU in tensorflow (CPU only supports CONV2D in channels last). I will be updating the repo to channels last to allow CPU inference.

The model is currently only trained on boxes, however I will be producing a model trained on both boxes and random drawings, for completeness.  This will likely coincide with the channels last update. 

Hope this helps :)

**Comment by ofirkris** [comment]
Great, thanks for uploading the model.
I'm curious to see how GanInverse + fully trained weights will impact results (pepsi++ took me 18 days to get to best checkpoints)

BTW here is another HiFill implementation - https://github.com/duxingren14/Hifill-tensorflow
