### ISSUE TITLE
I Can't Find the Aggregated Residual

### ISSUE THREAD

**Issue by Aaa-ChEn** [phillips96/CRA-Inpainting#3]
Sorry, I can't find the aggregated residual in trainer.py or infer.py, can you help me?
And I wonder whether the aggregated residual would be trained in training process, thank you very much!

**Comment by phillips96** [comment]
The 'CRAModel' is defined in the 'Utils/model.py' folder, so I suggest starting your reading there.

**Comment by Aaa-ChEn** [comment]
Sorry，I just find the attention_transfer used in Generator in Utills/model.py, but I still can't find the aggregated residual. Can you help me?
